### ISSUE TITLE
SourceConnector should balance configured topics across the tasks

### ISSUE THREAD

**Issue by dbtucker** [IBM/cloudant-kafka-connector#7]
It looks like you model is to dump all of the records from a single Cloudant database instance into the topics specified in the Source connector.   If that's the case, taskConfigs() method should probably assemble the property list for each subtask such that the topics are divided up (eg if the connector is configured for topics "holger", "david", and "adam" with a maxTasks of 2, you'd generate taskConfig property sets with "holger" and "adam" as one list of topics and "david" as the other).  I think that the current design will result in each record from the Cloudant database being written to every topic <maxTasks> times.

Long term, you could even extend this to work across the partitions in each topic ... but that's probably overkill.

**Comment by tomblench** [comment]
I experimented with this a while back, using the recommended recipe of calling `ConnectorUtils#groupPartitions` in `SourceConnector#taskConfigs`.

One quirk is that any writes to the "topics" task config are lost, because when the connector starts up, they are overwritten with the originals from the connector: https://github.com/a0x8o/kafka/blob/master/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/Worker.java#L399

We could still balance topics by writing to an internal, undocumented config and using that instead.

**Comment by tomblench** [comment]
Conclusion from discussion:
- Balancing across topics doesn't make sense, as they're probably all bound by the same Cloudant database bottleneck
- If multiple Cloudant databases are supported in future, then this is how tasks should be balanced/partitioned (see https://github.com/IBM/cloudant-kafka-connector/issues/86)

**Comment by tomblench** [comment]
See https://github.com/IBM/cloudant-kafka-connector/pull/87 - current behaviour is incorrect if `tasks.max` > 1
